name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels: ['feat','feature']
  - title: '🐞 Fixes'
    labels: ['fix','bug']
  - title: '🧰 Chores'
    labels: ['chore','refactor','docs','ci']

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

version-resolver:
  major:
    labels: ['major']
  minor:
    labels: ['minor','feat','feature']
  patch:
    labels: ['patch','fix','chore']
  default: patch

template: |
  ## Changes
  $CHANGES
